In [525]:
##library
import numpy as np
k = 12
L = 3
d = 4
N_g = 30
Bases=np.eye(12)
X0 = np.random.choice(a=12, size=4,replace=True )
X1 = np.random.choice(a=12, size=4,replace=True )
X2 = np.random.choice(a=12, size=4,replace=True )

B0=Bases[:,X0[:4]]
B1=Bases[:,X1[:4]]
B2=Bases[:,X2[:4]]


a0 = np.random.randn(4,30)/np.sqrt(12)
a1 = np.random.randn(4,30)/np.sqrt(12)
a2 = np.random.randn(4,30)/np.sqrt(12)
B0 = np.matmul(B0,a0)
B1 = np.matmul(B1,a1)
B2 = np.matmul(B2,a2)

F_cT=np.concatenate([B0,B1],axis=1)
F_cT=np.concatenate([F_cT,B2],axis=1)
F_c=np.transpose(F_cT)

kr_ = k
kc_ = k
n = 100
F_r = np.random.randn(n, k)
E = np.random.randn(n, L*N_g)
Q = np.random.randn(kr_, kc_)
Y_star=100*np.matmul(np.matmul(F_r,Q),F_cT)+E

In [526]:
lambda_= 10
rho_ = 2*1e2
mu_1 = 1e5
mu_2 = 1e5
beta_ = 1e2
tau_1 = 1e-5
tau_2 = 1e-2


In [527]:
kd_ = Y_star.shape[1] # of data
ob_mask = (np.random.uniform(low=0.0, high=1.0, size=(Y_star.shape[0], Y_star.shape[1]))>0.9).astype(int)

# ob_mask = np.round(np.random.rand(Y_star.shape[0], Y_star.shape[1]))
nob_mask = (ob_mask==0).astype(int)
km_ = np.sum((ob_mask==0).astype(int))

In [528]:
Y_bar=Y_star*ob_mask

In [529]:
c_int=np.zeros(Y_bar.shape[1])
c_int2=np.zeros(Y_bar.shape[1])

Eye_dict=np.eye(Y_bar.shape[0])
for ii in range(Y_bar.shape[1]):
    if ii==0:
        D_0 = np.reshape(Y_bar[:,ii],[Y_bar.shape[0],1])
        c_int[ii]=0
    else:
        D_0 = np.concatenate([D_0,np.reshape(Y_bar[:,ii],[Y_bar.shape[0],1])],axis=1)
        c_int[ii] = D_0.shape[1]-1
    D_0 = np.concatenate([D_0,np.transpose(Eye_dict[np.where(Y_bar[:,ii]==0)])],axis=1)
    c_int2[ii]=np.sum((Y_bar[:,ii]==0).astype(int))

In [530]:
c_int2

array([83., 90., 89., 92., 83., 84., 90., 90., 92., 91., 94., 97., 93.,
       92., 91., 95., 87., 90., 85., 89., 91., 86., 87., 93., 84., 90.,
       98., 95., 86., 95., 90., 91., 93., 87., 91., 91., 91., 94., 90.,
       93., 87., 87., 89., 93., 87., 91., 91., 86., 91., 89., 92., 93.,
       90., 92., 87., 95., 88., 90., 93., 96., 91., 90., 91., 86., 90.,
       87., 88., 94., 90., 91., 94., 90., 90., 92., 89., 89., 92., 91.,
       93., 89., 90., 88., 89., 91., 84., 87., 89., 92., 90., 92.])

In [531]:
c_int

array([   0.,   84.,  175.,  265.,  358.,  442.,  527.,  618.,  709.,
        802.,  894.,  989., 1087., 1181., 1274., 1366., 1462., 1550.,
       1641., 1727., 1817., 1909., 1996., 2084., 2178., 2263., 2354.,
       2453., 2549., 2636., 2732., 2823., 2915., 3009., 3097., 3189.,
       3281., 3373., 3468., 3559., 3653., 3741., 3829., 3919., 4013.,
       4101., 4193., 4285., 4372., 4464., 4554., 4647., 4741., 4832.,
       4925., 5013., 5109., 5198., 5289., 5383., 5480., 5572., 5663.,
       5755., 5842., 5933., 6021., 6110., 6205., 6296., 6388., 6483.,
       6574., 6665., 6758., 6848., 6938., 7031., 7123., 7217., 7307.,
       7398., 7487., 7577., 7669., 7754., 7842., 7932., 8025., 8116.])

In [532]:
kd_

90

In [533]:
C_0=np.random.randn(kd_, kd_)/np.sqrt(kd_*kd_)
for ii in range(kd_):
    C_0[ii,ii]=0
    x_i=np.random.randn(int(c_int2[ii]))
    x_i = np.reshape(np.append([1],x_i),[-1,1])
    if ii==0:
        A_0= np.matmul(x_i,np.reshape(C_0[ii],[1,-1]))
    else:
        A_0=np.concatenate([A_0,np.matmul(x_i,np.reshape(C_0[ii],[1,-1]))],axis=0)


Q_0= np.zeros((kr_,kc_))
Y_0= np.zeros((Y_star.shape[0],kd_))
Y_0 = Y_bar

# A_0= np.zeros((kd_+km_,kd_))
Z_0= np.zeros((kd_+km_,kd_))
V_0= np.zeros((kd_+km_,kd_))

G1_0= np.zeros((Y_star.shape[0],kd_))
G2_0= np.zeros((kd_+km_,kd_))
G3_0= np.zeros((kd_+km_,kd_))



# Q_0= np.random.randn(kr_, kc_)
# Y_0= np.random.randn(Y_star.shape[0], kd_)
# # Y_0 = Y_bar

# A_0= np.random.randn(kd_+km_, kd_)
# Z_0= np.random.randn(kd_+km_, kd_)
# V_0= np.random.randn(kd_+km_, kd_)

# G1_0= np.random.randn(Y_star.shape[0], kd_)
# G2_0= np.random.randn(kd_+km_, kd_)
# G3_0= np.random.randn(kd_+km_, kd_)


In [534]:
def svt(M,tau):
#     M = np.random.randn(30,20)
    zeros_1=np.zeros((M.shape[1],M.shape[1]))
    zeros_2=np.zeros((M.shape[0],M.shape[0]))
    mat_1=np.concatenate((zeros_1,np.transpose(M)),axis=1)
    mat_2=np.concatenate((M,zeros_2),axis=1)
    mat = np.concatenate((mat_1,mat_2),axis=0)
    iters=np.min([mat.shape[0],mat.shape[1]])
    kk=5
    while iters > 0:
        S, V = np.linalg.eig(mat)
        S_desc = np.sort(S)[::-1]
        sort_indices_desc = np.argsort(S)[::-1]    
        S_desc = S_desc[:kk]
        V_desc = V[sort_indices_desc]
        V_desc = V_desc[:kk]    
        mask_svt = np.where(S_desc>=tau)
        e = S_desc[mask_svt]
        w = V_desc[mask_svt]

        iters = iters - kk
        kk = np.min([kk+1,iters])
    S = e
    w = np.sqrt(2)*w

    U = np.abs(w[:,M.shape[1]:])
    V = np.abs(w[:,:M.shape[1]])
    return U, V

In [535]:
### PERFORMANCE ###
from numpy.linalg import inv
Y_ST=np.zeros((10000,Y_star.shape[0],Y_star.shape[1]))
for ii in range(100):
    Y_ST[ii]=Y_0
    A_0_k = np.matmul(inv(mu_2*np.matmul(np.transpose(D_0),D_0)+2*beta_*np.eye(kd_+km_)),mu_2*np.matmul(np.transpose(D_0),Y_0)+beta_*Z_0+beta_*V_0+G2_0+G3_0)
#     A_0_k = tau_1/(2*beta_*tau_1+mu_2)*(mu_2/tau_1*A_0-mu_2*np.matmul(np.transpose(D_0),(np.matmul(D_0,A_0)-Y_0))+beta_*(Z_0+V_0)+G2_0+G3_0)

    g_ = np.matmul(np.matmul(np.matmul(np.matmul(np.transpose(F_r),F_r),Q_0),np.transpose(F_c)),F_c)-np.matmul(np.matmul(np.transpose(F_r),(Y_0-(G1_0/beta_))),F_c)

    Q_0_k = tau_2/(beta_+tau_2)*(Q_0-tau_2*g_)


    Y_0_o=(mu_1*Y_0+mu_2*np.matmul(D_0,A_0)+beta_*np.matmul(np.matmul(F_r,Q_0),np.transpose(F_c))+G1_0)/(mu_1+mu_2+beta_)
    Y_0_n=(mu_2*np.matmul(D_0,A_0)+beta_*np.matmul(np.matmul(F_r,Q_0),np.transpose(F_c))+G1_0)/(mu_2+beta_)
    Y_0_k = ob_mask*Y_0_o + nob_mask*Y_0_n

    
    s_1=np.abs(A_0 - (G2_0/beta_))-(lambda_/beta_)
    s_1[s_1<0]=0
    s_2 = np.sign(A_0 - (G2_0/beta_))
    Z_c=np.multiply(s_1,s_2)
    Z_0_k = (A_0 - (G2_0/beta_))
    Z_0_k[c_int.astype(int)] = Z_c[c_int.astype(int)]

    
#     if ii==0:

    for jj in range(kd_):
        if jj==kd_-1:
            U, s, V = np.linalg.svd(A_0[c_int[jj].astype(int):,:]-(G3_0[c_int[jj].astype(int):,:]/beta_), full_matrices=True)
        else:
            U, s, V = np.linalg.svd(A_0[c_int[jj].astype(int):c_int[jj+1].astype(int),:]-(G3_0[c_int[jj].astype(int):c_int[jj+1].astype(int),:]/beta_), full_matrices=True)
        mask_svt = np.where(s>=(rho_/beta_))

        V_store=np.zeros((U.shape[0],kd_))        
        V_store[mask_svt,:]=V[mask_svt]
#         print(V_store)

        if jj==0:
            V_0_k = V_store
        else:
            V_0_k = np.concatenate([V_0_k,V_store],axis=0)

####   
#     for jj in range(kd_):
# #             print(jj)
#         if jj==kd_-1:
#             qq=A_0[c_int[jj].astype(int):,:]-(G3_0[c_int[jj].astype(int):,:]/beta_)
#             U, V =svt(A_0[c_int[jj].astype(int):,:]-(G3_0[c_int[jj].astype(int):,:]/beta_),rho_/beta_)
#         else:
#             qq=A_0[c_int[jj].astype(int):c_int[jj+1].astype(int),:]-(G3_0[c_int[jj].astype(int):c_int[jj+1].astype(int),:]/beta_)
#             U, V = svt(A_0[c_int[jj].astype(int):c_int[jj+1].astype(int),:]-(G3_0[c_int[jj].astype(int):c_int[jj+1].astype(int),:]/beta_),rho_/beta_)
# #                 print(V.shape,kd_,qq.shape[0],U.shape[0])
#         V_store=np.zeros((qq.shape[0],kd_))        
#         V_store[:V.shape[0],:]=V

#         if jj==0:
#             V_0_k = V_store
#         else:
#             V_0_k = np.concatenate([V_0_k,V_store],axis=0)


    G1_0=G1_0+beta_*(np.matmul(np.matmul(F_r,Q_0_k),np.transpose(F_c))-Y_0_k)
    G2_0=G2_0+beta_*(Z_0_k-A_0_k)
    G3_0=G3_0+beta_*(V_0_k-A_0_k)
    
    print(np.sum(np.abs(Y_0_k-Y_ST[ii])),np.linalg.norm(Y_0_k-Y_star,'fro')/np.linalg.norm(Y_star,'fro'))
    A_0= A_0_k
    Z_0= Z_0_k
    V_0= V_0_k
    Q_0= Q_0_k
    Y_0 = Y_0_k

102683.45458970236 0.9633360124886983
70685.85986997931 0.9537447419191125
54788.95868380892 0.9578651204273724


KeyboardInterrupt: 

In [517]:
Y_bar[:,0]


array([   0.        ,   62.96610047, -106.29506615,  -63.30250033,
       -157.72532635,  325.27523308,  135.90485091,    0.        ,
       -148.8423047 ,  267.00313802,  210.75376879,    0.        ,
       -482.24654038,    0.        ,  -71.17710017,  -25.46859774,
       -400.72544508,  -67.55030552, -551.01778367,   93.55404248,
         10.36672744,   17.72244161,  358.50021324,   -0.        ,
        330.97980426,   77.30619326,  391.90530991, -361.32633124,
       -159.35946499, -122.00987863,  333.16544752,  307.00844302,
        -70.37465138,   -0.        , -632.76663833,  602.28382871,
        320.87135492, -172.34178037, -406.20002568,  212.99434993,
         40.82562413, -443.01771424,  245.71457141, -586.78845428,
        -91.24302457,  349.6161375 ,    0.        ,  195.25872802,
          0.        , -243.12769319,  220.37982649,  270.72885657,
       -297.77963786,  474.7900996 ,  -12.4237739 , -167.64850685,
        229.7612676 ,  -60.17746775,  -58.32735692,  129.84718

In [518]:
Y_0[:,0]

array([ 2.32934411e-01,  2.94669123e+01, -5.00539752e+01, -2.97341378e+01,
       -7.37099672e+01,  1.52661620e+02,  6.36487611e+01,  1.22425279e+00,
       -6.99094414e+01,  1.25146931e+02,  9.89416729e+01,  7.55163052e-01,
       -2.26172901e+02,  6.40079452e-01, -3.33028925e+01, -1.20885431e+01,
       -1.87971499e+02, -3.17283893e+01, -2.58328072e+02,  4.37989671e+01,
        4.97041283e+00,  8.23344411e+00,  1.68072281e+02, -1.56227230e+00,
        1.55177587e+02,  3.61267552e+01,  1.83641670e+02, -1.69399325e+02,
       -7.48759063e+01, -5.71171726e+01,  1.56118635e+02,  1.43860784e+02,
       -3.30100164e+01, -1.54670183e-01, -2.96606418e+02,  2.82238425e+02,
        1.50538925e+02, -8.09489348e+01, -1.90437552e+02,  9.97201550e+01,
        1.92589041e+01, -2.07731285e+02,  1.15234910e+02, -2.75150008e+02,
       -4.27945915e+01,  1.63988263e+02, -1.00667413e-01,  9.16548803e+01,
        2.84289652e-01, -1.13874751e+02,  1.03256006e+02,  1.26949305e+02,
       -1.39643468e+02,  

In [309]:
Y_star[:,0]

array([ 715.41706205,  220.825109  , -305.36427906,  -84.72335939,
       -539.06432193,  469.57750258,   26.63688324,  506.94681712,
         73.79610753,   27.80137282,  826.18972499,   90.6266275 ,
        554.1027677 ,  617.73797919,  470.51455408, -928.19208613,
       -370.33201987,   87.53165429,  700.1898242 , -259.85347032,
       -196.47799566,  -72.47987092,  622.20768455,  299.32207519,
        221.22186546,  829.0049423 ,   40.22090451,  503.04785724,
         35.09692145,  235.06845776,    8.55687172, -357.5956285 ,
        227.1105543 , -366.80549229, -268.83957084,  330.74813673,
       -232.6080423 ,  204.5736629 ,  175.32656164,  173.48890845,
         54.64763   ,  423.12928747,  700.41745236, -543.43043619,
       -405.24481896,  228.0173257 ,  755.60778237, -203.03292396,
        258.17480096, -359.28041524,  -35.80949547, -715.28717926,
        475.76057579,  255.98902381,  186.73668901, -159.61740008,
       -200.86383408,  251.10417676, -324.4166057 ,  127.08012

In [88]:
np.linalg.norm(Y_0-Y_star,'fro')/np.linalg.norm(Y_star,'fro')

0.7519284285079888